'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Images',
      [
        {
          product_id: 1,
          src: 'https://ae01.alicdn.com/kf/HTB1XWErRFXXXXa8XXXXq6xXFXXXt.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 2,
          src: 'https://ae01.alicdn.com/kf/H62675a7cf8d4452984bc38fbb9d9e1827.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 4,
          src: '/img/forseLowWhiteAndBlue.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 4,
          src: '/img/forseLowWhiteAndBlue.1.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 4,
          src: '/img/forseLowWhiteAndBlue.3.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 4,
          src: '/img/forseLowWhiteAndBlue.4.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 6,
          src: '/img/forseFontanka.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 6,
          src: '/img/forseFontanka.1.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 6,
          src: '/img/forseFontanka.2.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 6,
          src: '/img/forseFontanka.4.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 6,
          src: '/img/forseFontanka.5.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 6 ,
          src: '/img/forseFontanka.6.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 6,
          src: '/img/forseFontanka.7.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 5,
          src: '/img/Yeezy500.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 5,
          src: '/img/Yeezy500.2.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 5,
          src: '/img/Yeezy500.3.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 5,
          src: '/img/Yeezy.5.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 3,
          src: '/img/forse1white.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 3,
          src: '/img/forse1white.2.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 3,
          src: '/img/forse1white.3.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 3,
          src: '/img/forse1white.4.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 3,
          src: '/img/forse1white.5.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 3,
          src: '/img/forse1white.6.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 7,
          src: '/img/Air Jordan 1 high zoom air cmft.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 7,
          src: '/img/Air Jordan 1 high zoom air cmft.1.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 7,
          src: '/img/Air Jordan 1 high zoom air cmft.2.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 7,
          src: '/img/Air Jordan 1 high zoom air cmft.3.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 7,
          src: '/img/Air Jordan 1 high zoom air cmft.4.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
       
        {
          product_id: 8,
          src: '/img/Air Jordan 1 Low SE "New Emerald".jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 8,
          src: '/img/Air Jordan 1 Low SE "New Emerald".1.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 8,
          src: '/img/Air Jordan 1 Low SE "New Emerald".2.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 8,
          src: '/img/Air Jordan 1 Low SE "New Emerald".3.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 8,
          src: '/img/Air Jordan 1 Low SE "New Emerald".4.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 9,
          src: '/img/Air Jordan 1 low se "Mighty swooshers".jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 9,
          src: '/img/Air Jordan 1 low se "Mighty swooshers".1.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 9,
          src: '/img/Air Jordan 1 low se "Mighty swooshers".2.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 9,
          src: '/img/Air Jordan 1 low se "Mighty swooshers".3.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 9,
          src: '/img/Air Jordan 1 low se "Mighty swooshers".3.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 10,
          src: '/img/Air Jordan 4 retro se "amethyst wave".1.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 10,
          src: '/img/Air Jordan 4 retro se "amethyst wave".2.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 10,
          src: '/img/Air Jordan 4 retro se "amethyst wave".3.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 10,
          src: '/img/Air Jordan 4 retro se "amethyst wave".4.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 10,
          src: '/img/Air Jordan 4 retro se "amethyst wave".5.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 11,
          src: '/img/Beentrill.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 11,
          src: '/img/Beentrill.1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 12,
          src: '/img/INXX STREET.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 12,
          src: '/img/INXX STREET.1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 13,
          src: '/img/New Balance 1906.1.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 13,
          src: '/img/New Balance 1906.2.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 13,
          src: '/img/New Balance 1906.3.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 13,
          src: '/img/New Balance 1906.4.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 13,
          src: '/img/New Balance 1906.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 14,
          src: '/img/New Balance 2002r.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 14,
          src: '/img/New Balance 2002r.1.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 14,
          src: '/img/New Balance 2002r.2.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 14,
          src: '/img/New Balance 2002r.3.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 14,
          src: '/img/New Balance 2002r.5.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 15,
          src: '/img/New Balance 9060 "WorkWear".1.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 15,
          src: '/img/New Balance 9060 "WorkWear".2.jpeg' ,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 15,
          src: '/img/New Balance 9060 "WorkWear".3.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 15,
          src: '/img/New Balance 9060 "WorkWear".4.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 15,
          src: '/img/New Balance 9060 "WorkWear".jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 16,
          src: '/img/New Balance 9060.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 16,
          src: '/img/New Balance 9060.1.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 16,
          src: '/img/New Balance 9060.2.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 16,
          src: '/img/New Balance 9060.3.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 16,
          src: '/img/New Balance 9060.4.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 16,
          src: '/img/New Balance 9060.5.jpeg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 17,
          src: '/img/Nike Dunk low SP community Garden.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 17,
          src: '/img/Nike Dunk low SP community Garden.1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 17,
          src: '/img/Nike Dunk low SP community Garden.2.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 17,
          src: '/img/Nike Dunk low SP community Garden.3.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 17,
          src: '/img/Nike Dunk low SP community Garden.4.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 18,
          src: '/img/Nike Dunk low turquoise.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 18,
          src: '/img/Nike Dunk low turquoise.1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 18,
          src: '/img/Nike Dunk low turquoise.2.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 18,
          src: '/img/Nike Dunk low turquoise.3.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 18,
          src: '/img/Nike Dunk low turquoise.5.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 19,
          src: '/img/Renmo.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 19,
          src: '/img/Renmo.1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 19,
          src: '/img/Renmo.2.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 20,
          src: '/img/Supreme Week 19 Gradient Stripe Beanie.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 21,
          src: '/img/The North Face 1996 bandana.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 21,
          src: '/img/The North Face 1996 bandana.1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 22,
          src: '/img/The North Face 1996 black .jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 22,
          src: '/img/The North Face 1996 black.1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 23,
          src: '/img/The North Face 1996 city.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 24,
          src: '/img/The North Face 1996 violet.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 24,
          src: '/img/The North Face 1996 violet.1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 25,
          src: '/img/The North Face 1996 whiteBandana.1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 25,
          src: '/img/The North Face 1996 whiteBandana.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 26,
          src: '/img/The North Face 1996 x in vincible.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 26,
          src: '/img/The North Face 1996 x in vincible.1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 27,
          src: '/img/The North Face 1996 x KAWS.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 28,
          src: '/img/The north face logo Jaket.1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 28,
          src: '/img/The north face logo Jaket.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 29,
          src: '/img/Cap.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 29,
          src: '/img/Cap1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 30,
          src: '/img/Champion T-shirt.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 30,
          src: '/img/Champion T-shirt.1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 31,
          src: '/img/Commission.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 32,
          src: '/img/ForHug T-shirt.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 32,
          src: '/img/ForHug T-shirt.1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 33,
          src: '/img/NB T-shirt beige.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 33,
          src: '/img/NB T-shirt beige.1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 34,
          src: '/img/NB T-shirt white.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 34,
          src: '/img/NB T-shirt white.1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 35,
          src: '/img/NB T-shirt white.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 35,
          src: '/img/NB T-shirt white.1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 36,
          src: '/img/Nike T-shirt black S.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 36,
          src: '/img/Nike T-shirt black S.1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 37,
          src: '/img/Stussy T-shirt black.1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 37,
          src: '/img/Stussy T-shirt black.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 38,
          src: '/img/Supreme T-shirt.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 39,
          src: '/img/THF T-shirt beige.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 39,
          src: '/img/THF T-shirt beige.1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 40,
          src: '/img/THF T-shirt black.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 40,
          src: '/img/THF T-shirt black.1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 41,
          src: '/img/thf t-shirt top.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 41,
          src: '/img/thf t-shirt top.1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 42,
          src: '/img/TNF T-shirt beige S.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 42,
          src: '/img/TNF T-shirt beige S.1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 43,
          src: '/img/TNF T-shirt love.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 43,
          src: '/img/TNF T-shirt love.1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
       
        {
          product_id: 44,
          src: '/img/TNF t-shirt summer.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 44,
          src: '/img/TNF t-shirt summer.1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 45,
          src: '/img/TNF T-shirt white.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 45,
          src: '/img/TNF T-shirt white.1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 46,
          src: '/img/VANS T-shirt white.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          product_id: 46,
          src: '/img/VANS T-shirt white.1.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Images', null, {});
  },
};
